name: Columns
version: '${project.version}'
main: org.koteyka.columns.ColumnsPlugin
api-version: '1.16'
commands:
  start:
    description: start the game!
    permission: columns.cmd.start
    permission-message: НЕЛЬЗЯ
    usage: /<command>
permissions:
  columns.cmd.start:
    description: command start game
    default: op