name: Columns
version: '${project.version}'
main: org.koteyka.columns.ColumnsPlugin
api-version: '1.16'
commands:
  start:
    description: start the game!
    permission: columns.cmd.start
    permission-message: НЕЛЬЗЯ
    usage: /<command>
  event:
    description: event!
    permission: columns.cmd.event
    permission-message: НЕЛЬЗЯ
    usage: /<command>
  finish:
    description: finish!
    permission: columns.cmd.finish
    permission-message: НЕЛЬЗЯ
    usage: /<command>
permissions:
  columns.cmd.start:
    description: command start game
    default: op
  columns.cmd.event:
    description: command event in game
    default: op
  columns.cmd.finish:
    description: command finish game
    default: op